### ISSUE TITLE
[Global State Management] Manage data globally

### ISSUE THREAD

**Issue by Ts-A** [warmachine028/uemcrp#102]
### Description

Currently the data is handled locally in components using useState and passed down as props throughout all the components that work on that data. For eg: user State is managed in App Component and passed down as props to many components down. With the introduction of redux, the data can be managed globally and called upon when needed. This could reduce code complexity during future client development and can also help when starting to integrate with backend later.

### Screenshots

![UEMCRP4](https://user-images.githubusercontent.com/66743734/197343467-73f631c2-d975-43a8-bcb9-1d0fd7300524.png)

### Additional information

- Always use styled componets instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Ts-A** [comment]
Tools to use: react-redux and @reduxjs/toolkit

**Comment by warmachine028** [comment]
Yes it is necessary. I was confused between using Redux or React Query mentioned in [this video](https://youtu.be/Kjkx2BASAZA). What are your thoughts on using React Query over Redux as the React Query seems a bit easier to manage than Redux. I have used Redux in one of my other [project](https://github.com/warmachine028/memories).

**Comment by Ts-A** [comment]
React Query is definitely powerful when managing with asynchronous data. So we can separate client side (theme) and server side(user) data along with the data fetching optimizations it brings. I was with the mindset of @reduxjs/toolkit, but react-query seems better too.

**Comment by Ts-A** [comment]
I suppose to use react-query with the current state of the project, we would have to update the server part of the application first before using it, as react-query's main use is async data management.

**Comment by warmachine028** [comment]
Would you be able to update the server for the implementation of react-query in this project? It would be a great help!

**Comment by Ts-A** [comment]
Sure thing. I can work on the server part and come back to react-query.

**Comment by warmachine028** [comment]
Great 👍 😃. Assigning you!

**Comment by Ts-A** [comment]
Do you have a model DB schema and the routes to be present in backend?

**Comment by Ts-A** [comment]
For now, there's only a sample user schema and user CRUD routes, not the actual one i suppose.

**Comment by warmachine028** [comment]
Yes

**Comment by Ts-A** [comment]
Where could I get that?

**Comment by warmachine028** [comment]
Can you create some mock users for now?

**Comment by Ts-A** [comment]
@warmachine028 implemented bare minimum of react-query setup in project but it's not the efficient way yet. Simply because currently there are too many optimizations to be done in client part with state management. As react-query handles async server data, it is wise to first re-structure the state management through the app accurately and then implement react-query.

**Comment by Ts-A** [comment]
It is best if I create a new issue for optimizing state management using either context APIs and reducers first for both client and server data. And jump to react-query setup removing the server dependent data. @warmachine028 your thoughts?

**Comment by Ts-A** [comment]
It primarily affects in react-query with auth, since it has parts of client and server state

**Comment by warmachine028** [comment]
> It is best if I create a new issue for optimizing state management using either context APIs and reducers first for both client and server data. And jump to react-query setup removing the server dependent data. @warmachine028 your thoughts?

I think its a good idea. You can create a new issue
