### ISSUE TITLE
[Enhancement] <State Management using Context and Reducer>

### ISSUE THREAD

**Issue by Ts-A** [warmachine028/uemcrp#105]
### Description

Migrate from local state management to global state management.

### Additional information

- Always use styled componets instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by anuj98** [comment]
Are you considering using context or Redux here?

**Comment by anuj98** [comment]
Also when are you planning to add UI for update info page? I would like to work on that.

**Comment by warmachine028** [comment]
@anuj98 we are planning to avoid redux as of now and instead use react-query as discussed in

**Comment by anuj98** [comment]
> Also when are you planning to add UI for update info page? I would like to work on that.

What about this?

**Comment by warmachine028** [comment]
> > Also when are you planning to add UI for update info page? I would like to work on that.
> 
> What about this?

Could you create a new issue for the Update Info UI. I would assign you
