### ISSUE TITLE
[FEATURE]  Making the grid items clickable only when hovering over the pictures

### ISSUE THREAD

**Issue by boltkk95** [warmachine028/uemcrp#106]
### Description

In the  dashboard, the object tiles below student details (the grid items) are clickable even in the whitespace (takes you to that tile's page. Could make it clickable only when hovering on pictures.

### Additional information

- Always use styled componets instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by boltkk95** [comment]
can i work on this issue?

**Comment by warmachine028** [comment]
Sure!

**Comment by warmachine028** [comment]
Make sure to star this repository

**Comment by boltkk95** [comment]
ok. got it.
thanks

**Comment by boltkk95** [comment]
@warmachine028  i have issued the PR for this issue.
