### ISSUE TITLE
changing the curser to pointer 

### ISSUE THREAD

**Issue by boltkk95** [warmachine028/uemcrp#108]
### Description

When hovering over student profile picture to upload new picture, the cursor should be pointer

### Additional information

- Maintain Folder Structure
- Always use styled componets and MUI components instead of plain CSS.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by boltkk95** [comment]
@warmachine028  forgot to change the curser when i was doing the profile picture feature, can you assign me this? will get it done asap

**Comment by warmachine028** [comment]
This is a minor issue, but I'm still assigning you.
