### ISSUE TITLE
[FEATURE] calendar enhancement

### ISSUE THREAD

**Issue by boltkk95** [warmachine028/uemcrp#110]
### Description

In calendar page, the panel on the left with holidays could have clickable buttons with clicking a specific holiday takes you to that date in the calendar.

### Additional information

- Always use styled componets instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by boltkk95** [comment]
@warmachine028 what do you think about this? can you assign me this?

**Comment by warmachine028** [comment]
Definitely an important feature! It would Very nice if someone could implement that!

**Comment by warmachine028** [comment]
Yes! I will assign you

**Comment by boltkk95** [comment]
@warmachine028
