### ISSUE TITLE
Console has errors related to keys

### ISSUE THREAD

**Issue by anuj98** [warmachine028/uemcrp#111]
### Description

- When we open the Unit test details page there are console errors. We can similarly check other pages and make sure there are not console errors.
This is an easy fix. We should add keys while rendering some div in a loop.

- Also making sure there are not console logs while merging code is important 

### Screenshots

![image](https://user-images.githubusercontent.com/30874550/198831035-922c9ae2-53f0-43e1-9662-74812f9602b5.png)

### Additional information

- Maintain Folder Structure
- Always use styled componets and MUI components instead of plain CSS.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
You can solve this error. I am assigning this to you.

**Comment by anuj98** [comment]
Found few unused imports. Should I remove those as well?

**Comment by warmachine028** [comment]
Yes please

**Comment by anuj98** [comment]
Done
