### ISSUE TITLE
[FEATURE] Add UI for Update Info page

### ISSUE THREAD

**Issue by anuj98** [warmachine028/uemcrp#114]
### Description

Currently the Update Info page has no UI and functionality. Design to be discussed with team and implemented.
https://github.com/warmachine028/uemcrp/issues/105#issuecomment-1296215863

### Screenshots

![image](https://user-images.githubusercontent.com/30874550/199249836-30f4afd0-0539-4df9-8d74-81115cca2f67.png)

![image](https://user-images.githubusercontent.com/30874550/199250329-23cb67a7-845b-4b16-8dc6-d6753e26f486.png)

### Additional information

- Always use styled componets instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by anuj98** [comment]
@warmachine028 Can we remove the hacktoberfest label now? I think I won't be able to you can remove it if we think it's no longer required.

**Comment by warmachine028** [comment]
I have assigned you. I will remove the `hactoberfest` label

**Comment by anuj98** [comment]
Following are the things I guess can be updated:

- Phone number
- Email
- Home Address

Anything else apart from this? Name I guess won't be directly updated. Would need approvals, correct?

**Comment by warmachine028** [comment]
Yes. For now these are fine.

**Comment by anuj98** [comment]
@warmachine028 Any suggestion on this:
![image](https://user-images.githubusercontent.com/30874550/199662387-6d9e4ae3-db0b-4915-a358-778c2fa50d7f.png)

**Comment by warmachine028** [comment]
I think this one looks perfect. Doesn't need to be mobile responsive for now, if it's already done then it's fine. Else I will create a new Issue for that seperately .

**Comment by anuj98** [comment]
> I think this one looks perfect. Doesn't need to be mobile responsive for now, if it's already done then it's fine. Else I will create a new Issue for that seperately .

Already done. Attached a screenshot in PR
