### ISSUE TITLE
Responsiveness Bug in Home

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#115]
### Description

- This Dashboard section in Home page is not sized properly in Mobile View. 
- This needs to be fixed asap. 

### Screenshots

![IMG_20221101_203935](https://user-images.githubusercontent.com/75939390/199267380-4572d8db-9284-4ab7-bc90-a37506299f8a.jpg)

### Additional information

- Maintain Folder Structure
- Always use styled componets and MUI components instead of plain CSS.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by elidakirigo** [comment]
hello there, I'd love to assist, kindly assign.

**Comment by warmachine028** [comment]
Sure I'll assign you

**Comment by warmachine028** [comment]
Hello @elidakirigo. What is the status of the work?

**Comment by githmin** [comment]
Hello there, I'd like to work on fixing this

**Comment by warmachine028** [comment]
Sure
