### ISSUE TITLE
Private Routes are not protected

### ISSUE THREAD

**Issue by Komal1234144** [warmachine028/uemcrp#123]
### Description

If we change the url to a private route from the bar itself , the page gets navigated to it without having to log in.  Is it a mistake or has been kept like this intentionally so as to allow the contributors to check  out the website. By the way , the  responsiveness looks fine. What kind of improvement are we expecting ?

### Additional information

- Maintain Folder Structure
- Always use styled componets and MUI components instead of plain CSS.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
@Komal1234144 This is happening because we haven't created the backend for user authentication yet. The modiles
