### ISSUE TITLE
Figma Design - Home 🏡

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#13]
### Description

Uemcrp requires a Figma Layout for Home Page.
- Create figma files inside `design/` folder in **Root** directory only.
- Designs need not be perfect but must be done sincerely and carefully

### Screenshots

- Please refer to #5 for screenshots

## Happy contributing. 💐

**Comment by NAVONIL-PAUL** [comment]
I want to work on this

**Comment by warmachine028** [comment]
Sure! go ahead. Please try to complete the work before this weekend, so that we won't be burdened by the college works. It needs not to be perfect. But it must be mostly accurate and sincerely done. If you get stuck or are facing any problem, make sure to let me know. I'll asist you. 

**Please make sure to set up the project locally, and study the page with mobile responsiveness before working on the design.** 

Cheers,
Pritam

**Comment by NAVONIL-PAUL** [comment]
Yes, I will try to finish it on time.

**Comment by anurupadas7** [comment]
Hey Pritam, ready to work on this.

**Comment by warmachine028** [comment]
Go ahead with it
