### ISSUE TITLE
Title & Tab Bar Icon

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#16]
### Description

- The title is React App which must be changed to **UEMCRP** (All Caps)
- Also the React Logo must be replaced by UEM Logo.
- The UEM Logo can be found in `assets` folder.
- Hint: You must make changes in `client/public/index.html`

### Screenshots

![basic](https://user-images.githubusercontent.com/75939390/187034598-de9ecfc7-8b19-496c-9c10-b930c9485adc.jpg)

## Happy contributing. 💐

**Comment by developer-irfan** [comment]
@warmachine028 assign me this task. i will correct all of these you mentions.

**Comment by warmachine028** [comment]
Very Good! Go ahead with it.
Please leave a star. This is a fairly new Project and requires your help.

**Comment by developer-irfan** [comment]
@warmachine028 ok
