### ISSUE TITLE
Sign in button 

### ISSUE THREAD

**Issue by Sohelahmed-molla** [warmachine028/uemcrp#18]
### Description

- The problem is with the sign in button. 
- When we hover the button it just get disappear.

### Screenshots

![Screenshot (133)](https://user-images.githubusercontent.com/73135042/187036976-b3664000-df26-403f-948b-2915c3baec0a.png)
![Screenshot (135)](https://user-images.githubusercontent.com/73135042/187037049-278e92cd-88f2-4f1a-8dbb-33d0d56883dd.png)

_No response_

### Additional information

we just have to change the background color of the sign in button and make the font-weight bold.

**Comment by warmachine028** [comment]
Sure! Go ahead with it! Please complete this issue before the weekend so that college work doesn't burden us. Make sure to star the Repo. 

Cheers
Pritam
