### ISSUE TITLE
Dummy Modules and Routes 🛣️

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#19]
### Description

- Currently all modules take us to a route, but the routes are not operational.
- Routes need to be created inside `App/index.jsx` folder.
- Also Dummy Modules must be created inside `studentModules` directory, in the same format as other dummy modules present inside it. Right now **no module needs to be designed**, only the dummy modules must be created.
- Currently there are 9 modules in studentDashboard. Out of which 2 are already created for reference i.e `AdmitCard` & `ChangePassword`
- Make sure to follow the format already created.
- All modules created must be exported from `studentModules/index.js` like the previous ones.
- All the route links can be found inside `data/dashboard.js` collection.

### Screenshots

- ### Dashboard Actions
![mod](https://user-images.githubusercontent.com/75939390/187037670-a18ff901-5d22-41e8-9a1f-5da6ab7f7869.jpg)

- ### Reference 1
![reference 2](https://user-images.githubusercontent.com/75939390/187037715-986aed78-a810-43f9-829c-7cbb45b298f8.jpg)

- ### Reference 2
![reference](https://user-images.githubusercontent.com/75939390/187037717-615a458b-bd52-4032-a3cc-c5e813af5a4c.jpg)

- ### Folder Structure:
![folder structure](https://user-images.githubusercontent.com/75939390/187037921-92c76abb-c249-4001-ae89-860abf43adea.jpg)

- ### Reference for changes in `App/index.jsx`
![app jsx](https://user-images.githubusercontent.com/75939390/187038021-647dd694-4b28-4a5f-af96-d255d44a2f44.jpg)

### Additional information

- All Dummy Modules must be created inside `studentModules`. Folder structure must be maintained like this.

**Comment by Sohelahmed-molla** [comment]
I would like work on this issue... ✌

**Comment by warmachine028** [comment]
Sure! Go shead
