### ISSUE TITLE
Change Password Module 👁️👁️‍🗨️

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#28]
### Description

- Password reset page must be designed for UEMCRP.
- The file must be created inside `studentModules/changePassword` directory. 
- A dummy component is already created there 
- The form component from Auth Page must be reused.
- No need to write any validation or form submit logic. Just the basic layout is required by reusing the form component from `Auth/`
- There must be only **3 Text Fields**.
- And 1 submit Button.

### Screenshots

- ### Module to be designed
![IMG_20220829_022426](https://user-images.githubusercontent.com/75939390/187094351-d3e0bdc5-af44-46f3-bcf5-d83f6191b956.jpg)

- ### Pre written Route 
![reference](https://user-images.githubusercontent.com/75939390/187037717-615a458b-bd52-4032-a3cc-c5e813af5a4c.jpg)

- ### Original Website Reference 

![IMG_20220829_023409](https://user-images.githubusercontent.com/75939390/187094453-3b5f9a6c-ae1e-4bb5-9d5d-7cab759f3555.jpg)

- ### Folder Structure:
![folder structure](https://user-images.githubusercontent.com/75939390/187037921-92c76abb-c249-4001-ae89-860abf43adea.jpg)

### Additional information

- Use styled components and Material UI only 
- Please maintain the Folder structure

**Comment by Sohelahmed-molla** [comment]
I would like to work on this  issue...

**Comment by warmachine028** [comment]
Very Good. Go ahead with it! Keep up with this enthusiasm! 🎉

**Comment by warmachine028** [comment]
Great work @Sohelahmed-molla ✅
