### ISSUE TITLE
Organizational Calendar 📆🗓️

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#32]
### Description

- Organizational Calendar must be designed for UEMCRP
- Currently the original Page of [iemcrp] logs the user out to redirect to the organizational calendar.
- This action is really cumbersome for the users.
- The component must be designed using MUI and Styled Components only. 

[iemcrp]: https://www.iemcrp.com/

### Screenshots

- The module

![org](https://user-images.githubusercontent.com/75939390/187486375-63f1b5bb-3df5-4f80-9635-95b4dffb8242.png)

- Suggested usage of components:

![calendar](https://user-images.githubusercontent.com/75939390/187487540-3032d8f1-01f4-41aa-9126-c1e7042744f3.jpg)

- Folder Structure

![187472211-54602d24-d4c0-477f-b1b6-602e38182a77](https://user-images.githubusercontent.com/75939390/187486398-816f0fd6-1669-4745-9941-206a8a957595.jpg)

### Additional information

- Only MUI and Styled components must be used
- Take reference from MUI Documentation about [Date pickers](https://mui.com/x/react-date-pickers/date-picker/) and [Date Range Pickers](https://mui.com/x/react-date-pickers/date-range-picker/)
- All folder structures must be maintained

## Happy contributing. 💐

Star my other Repositories [here](https://github.com/warmachine028)

**Comment by anuj98** [comment]
Will this be just a date range selector inside the calendar page?

**Comment by warmachine028** [comment]
Only a data range Selector will do fine for now. Currently it just needs to look like a calendar page with 12 months.

**Comment by anuj98** [comment]
Ok I would like to try this out.

**Comment by warmachine028** [comment]
Great Go ahead with it!

**Comment by anuj98** [comment]
I don't think we can create a whole 12-month calendar using material UI datepicker. Any suggestions from your end

**Comment by warmachine028** [comment]
Is it not possible to create like this?
![Screenshot 2022-09-04 123633](https://user-images.githubusercontent.com/75939390/188301746-60f5ccaa-91c1-4184-a7c0-346fe2ecfa14.jpg)

**Comment by anuj98** [comment]
Yes this is possible. I thought whole 12 months on the screen.

**Comment by warmachine028** [comment]
Yes I wanted like this image

**Comment by anuj98** [comment]
But there's 1 problem That date picker is requires pro license.

**Comment by warmachine028** [comment]
Alright! So this can't be done using material UI components itself. Can you try using [React Calendar](https://www.npmjs.com/package/react-calendar)

**Comment by anuj98** [comment]
I raised a PR but not sure all the build activities failed. Also, the package lock got a lot of changes along with version. Can you check and let me know what's the issue?

**Comment by warmachine028** [comment]
I will let you know about the issue by tomorrow
