### ISSUE TITLE
Mobile Responsiveness 📱

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#33]
### Description

- The Admit Card Page is not Responsive.
- The layout must be made responsive.
- Changes in styles files of the components must be done using media breakpoints
- References can be taken from other component's styles files which contain media breakpoints, such as auth or home
- **The Admit Card itself must not be modified inside(only the outer container must be modified) as it is a A4 size Static page which is created as a preview to be downloaded by user as PDF.** You can add Overflow to make the page responsive.

### Screenshots

- Mobile responsiveness landscape
![admit](https://user-images.githubusercontent.com/75939390/187489346-6cf87fc0-a7f3-4312-8694-e34fcf0f6333.jpg)

- Mobile Responsiveness portrait
![admit2](https://user-images.githubusercontent.com/75939390/187489455-e5386fba-e614-434f-9e22-3c9e84fb2c37.jpg)

## Happy contributing. 💐

Star my other Repositories [here](https://github.com/warmachine028)

**Comment by zuzexx** [comment]
Can I be assigned to this issue?

**Comment by warmachine028** [comment]
Go ahead with it
