### ISSUE TITLE
Logout Button Invisible on Hover

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#38]
### Description

- The logout button becomes invisible on hover
- This action must be changed and a lighter shade of black must be added to the hover.

### Screenshots

- This is the preview of the bug.

![hover](https://user-images.githubusercontent.com/75939390/187739426-8c6e3329-c9f0-40b3-ac38-7af2fc7c7011.jpg)

### Additional information

- A [similar issue](#18) has occurred below, so you can take suggestions from there too 
---

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Marsh-sudo** [comment]
like to give this a short

**Comment by warmachine028** [comment]
Go ahead with it

**Comment by seddboi** [comment]
Hello there, I have solved the invisible button issue on hover 🙂... please add me to the project.

**Comment by warmachine028** [comment]
@seddboi you have to create a PULL REQUEST by completing the Pull Request template adding issue name, issue number and your name after making the  changes. Please go through contributing.md file for more detailed informations

**Comment by warmachine028** [comment]
Hi @Marsh-sudo what's the status of the Work?

**Comment by warmachine028** [comment]
> Hello there, I have solved the invisible button issue on hover 🙂... please add me to the project.

I have assigned you this Issue. Please create a PR now
