### ISSUE TITLE
Attendance Form Icon 🃏

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#47]
### Description

- There is an icon missing in the Attendance Form
- This must be fixed
- Only use Icons from `@mui\Icons`
- The Icon is already imported, only place the icon in the form component

### Screenshots

- Problem
![Screenshot 2022-09-02 231730](https://user-images.githubusercontent.com/75939390/188209552-31724f5c-8457-4425-a37b-b40fc5c4a526.jpg)

- Final Solution
![issue](https://user-images.githubusercontent.com/75939390/188209722-dae070d2-fb51-47ed-bb17-7c816df2e316.jpg)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by sreekeshiyer** [comment]
I started working on this issue, sorry I forgot to update it here.

**Comment by warmachine028** [comment]
Very good
