### ISSUE TITLE
Figma Design - Auth 📔 🧧

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#5]
### Description

# Uemcrp requires a Figma Layout. 

- Initially just the only the `auth` page layout is acceptable
- Create figma file inside the `designs/` folder.
- Designs need not be perfect but must be done sincerely and carefully 

### Screenshots

- Example: 

![example](https://user-images.githubusercontent.com/75939390/186491127-f0e64e38-c0c2-4fa0-9587-8204ff10e87a.jpg)

## **Make sure to read the [CONTRIBUTING](https://github.com/warmachine028/uemcrp/blob/main/CONTRIBUTING.md) and [SETUP](https://github.com/warmachine028/uemcrp/tree/main/rules) docs before proceeding**
- Contributors are supposed to run the project, study and explore the page before proceeding to create figma design files. 

## Happy contributing. 💐

**Comment by NAVONIL-PAUL** [comment]
I want to work on the Figma designing part.

**Comment by warmachine028** [comment]
> I want to work on the Figma designing part.

Another person is already working on the issue, i would request you to wait.
