### ISSUE TITLE
Mobile Responsiveness - Bills 📱

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#53]
### Description

- The Bills page is not responsive yet
- The layout can be made responsive using flexBoxes
- Use breakpoints in `styles.js` of `studentModules\Bills` folder.

### Screenshots

- Padding Required
![padding](https://user-images.githubusercontent.com/75939390/188257858-ad9566b6-6e84-40e7-88c9-dc9284b50a3b.jpg)

- Use flexDirection: column
![fdc](https://user-images.githubusercontent.com/75939390/188257929-18a7a0e6-48f8-40f6-bfbe-3280fcf25385.jpg)

### Additional information

- Use only styled components and JSX.
- Maintain code structure.
- Do not install any Additional modules

## Additional information
Make sure to read the [CONTRIBUTING](https://github.com/warmachine028/uemcrp/blob/main/CONTRIBUTING.md) and [SETUP](https://github.com/warmachine028/uemcrp/tree/main/rules) docs before proceeding
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by erfan93na** [comment]
I'd be happy to do this.

**Comment by warmachine028** [comment]
@erfan93na Go ahead with it !
