### ISSUE TITLE
Faculty Name Bug  🐛

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#57]
### Description

- Faculty name toolTip must not be shown in the RECESS column of Academic Time Table.
- This must be removed.

### Screenshots

![new issue](https://user-images.githubusercontent.com/75939390/188295739-6ac72d54-5837-4473-b1b6-220f541ded68.jpg)

### Additional information

- All other files must be kept intact

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by anuj98** [comment]
@warmachine028 Can you assign me this issue? I am new to contributing to open source projects, so wanted to start with easier once.

**Comment by warmachine028** [comment]
Go ahead with it!

**Comment by anuj98** [comment]
There's not file in server folder. How do I get it?

**Comment by warmachine028** [comment]
> There's no file in server folder. How do I get it?

Yes the server isn't created yet. currently we are working with hard coded data only.
Did you `git clone` the repository?

**Comment by anuj98** [comment]
Yes I forked and cloned
Also, I am facing issues with the `progress` packages:
<img width="938" alt="image" src="https://user-images.githubusercontent.com/30874550/188297721-56f4fb9c-a10e-4bbc-b16f-be87e27df922.png">

**Comment by warmachine028** [comment]
> Yes I forked and cloned Also, I am facing issues with the `progress` packages: <img alt="image" width="938" src="https://user-images.githubusercontent.com/30874550/188297721-56f4fb9c-a10e-4bbc-b16f-be87e27df922.png">

did you try `npm install` to fix it ?

**Comment by anuj98** [comment]
Yes I did `npm install` in cleint folder

**Comment by warmachine028** [comment]
can you show me your package.json file

**Comment by anuj98** [comment]
<img width="246" alt="image" src="https://user-images.githubusercontent.com/30874550/188297904-4cd2518a-0b3d-484d-b428-a64f719fc014.png">

**Comment by warmachine028** [comment]
- Can you try uninstalling the package [@progress/kendo-react-pdf](https://www.npmjs.com/package/@progress/kendo-react-pdf) and then reinstalling it. 
- If that doesn't work you can comment out the admit card module and work on the TimeTable only

**Comment by anuj98** [comment]
@warmachine028 Created a PR. Please take a look.

**Comment by warmachine028** [comment]
Very Good! Welcome to the Contributor's Club. Make sure to star this project 🥂

**Comment by anuj98** [comment]
I guess you'll be merging the PR. I don't have write access.

**Comment by warmachine028** [comment]
Yes! I will merge it
