### ISSUE TITLE
Update README.md 📝🗒️

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#58]
### Description

- The following images are outdated in the `README.md`'s Demo section.
- They must be replaced with new ones.
- The images must be downloaded from this issue 
- Then replaced inside `assets/` folder.

### Screenshots

- ### README.md DEMO section (For Reference)
![Web capture_4-9-2022_9041_github com](https://user-images.githubusercontent.com/75939390/188295907-e617fd67-f0b0-478b-a223-ac344e59f363.jpeg)

- ### New Images:
1. 
![mobile](https://user-images.githubusercontent.com/75939390/188295915-16498dd4-a261-45b3-8c23-93620e705238.png)

2. ![ipad](https://user-images.githubusercontent.com/75939390/188295912-bbdef930-7427-4f47-a7a5-148857d823a4.png)

3. ![macbook](https://user-images.githubusercontent.com/75939390/188295914-e19a40f4-60f2-432e-bab6-db84b64d3fd8.png)

### Additional information

- **No other files must be modified**
- Files must be downloaded and kept inside `assets/` folder only

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by VedanthB** [comment]
I'd like to take this up.

**Comment by warmachine028** [comment]
Yes go ahead with it!

**Comment by VedanthB** [comment]
okay.

**Comment by warmachine028** [comment]
@VedanthB you can also look at this [issue](https://github.com/warmachine028/uemcrp/issues/37), it requires just a simple markdown addition
