### ISSUE TITLE
PlaceHolder text

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#6]
### Description

The placeholder text reads Enrollment number, but the teachers might not particularly have enrollment number though. They might have employee Number.
 - change placeholder text from "Enrollment no." to User Name in Auth
 - change Select box title "Teachers" to " Teachers and Staffs"
 

### Screenshots

![Screenshot_2022-08-25-19-35-38-16_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/75939390/186686708-6546c3ab-8841-47d8-83d2-a8eb94ebeee4.jpg)

**Comment by Sohelahmed-molla** [comment]
I think it will work...

**Comment by warmachine028** [comment]
Sure, Go ahead ✅

**Comment by Sohelahmed-molla** [comment]
I am having net issues... 
I have already committed....
What u ask me to do.... 
Can u plz check the code once...

**Comment by warmachine028** [comment]
Can you put the screenshot of the changes you made, here?

**Comment by Sohelahmed-molla** [comment]
![Screenshot (129)](https://user-images.githubusercontent.com/73135042/186979690-6e70eab9-cfe4-43d9-ab1c-967bfd443ffd.png)

**Comment by Sohelahmed-molla** [comment]
![Screenshot (131)](https://user-images.githubusercontent.com/73135042/186980498-4dcaf44c-e91d-47a6-a28a-fd64ae1e3d84.png)

**Comment by warmachine028** [comment]
> ![Screenshot (131)](https://user-images.githubusercontent.com/73135042/186980498-4dcaf44c-e91d-47a6-a28a-fd64ae1e3d84.png)

Hi @Sohelahmed-molla, Great to see you fixed the first Bug in this project and made your first contribution.

You can create a PR with this screenshot. If you are having trouble completing the PR template, make sure to check out any previously closed PR in this repo which contains the completed format of completing the PR template.

Great Work,
Pritam
