### ISSUE TITLE
University Marking System 🗒️📝

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#69]
### Description

- The university Marking System Module is not yet designed
- Currently the module does nothing but display a text
- The module must be designed using Material UI only
- There must be a drop Down to select semesters
- You may refer to the given screenshots 
- This must be mobile responsive in all devices

### Screenshots

![Screenshot 2022-10-02 093724](https://user-images.githubusercontent.com/75939390/193437469-93e540f5-2262-4545-883a-6894532a03d7.png)

- Original wepPage for reference
![Screenshot 2022-10-02 093150](https://user-images.githubusercontent.com/75939390/193437321-04a3d950-6fb8-4a86-9c2f-6d4158078286.png)

### Additional information

- Maintain Folder Structure
- Do not use bare HTML and CSS, instead use JSX and Styled Components only
- Stick with material UI
- The design must strictly follow mobile responsiveness
- Do complete the PR Template for successful merge

### Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by sangmesh04** [comment]
I would like to work on this. Can you assign it to me?

**Comment by warmachine028** [comment]
Great! ❤️. Go ahead with it.
