### ISSUE TITLE
Remove Name Field

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#70]
### Description

- The Icon already has a name below it.
- Name Component must not be present in the paper
- Remove the Name component

### Screenshots

![Screenshot 2022-10-04 103530](https://user-images.githubusercontent.com/75939390/193738960-ba9a3758-4a7f-416c-8c34-cd7b01375312.png)

### Additional information

- Please star this repo 🌟
- Make sure to read All contributing guidelines
- Also complete the Pull Request template stating your name and proper screenshots

**Comment by GabrielWarner** [comment]
Hello I can do this. Can you assign it to me?

**Comment by warmachine028** [comment]
Sure!

**Comment by GabrielWarner** [comment]
Thank you, getting it cloned now.

**Comment by ABHISHEK-PANDEY2** [comment]
Can i work on it too ? already started , didn't saw Gabriel was assigned

**Comment by warmachine028** [comment]
Hey @ABHISHEK-PANDEY2, glad to see your enthusiasm towards the project. However as @GabrielWarner was already assigned to this issue, I would like you:
 - To find other issues to contribute.
 - Create a new issue stating ways to improve this project.
 - wait for new issues to be created.

**Comment by ABHISHEK-PANDEY2** [comment]
@warmachine028 Ok , thanks for the reply 😄

**Comment by warmachine028** [comment]
@ABHISHEK-PANDEY2 check out #71
