### ISSUE TITLE
Unresponsive Module

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#71]
### Description

- The organisational calendar module is unresponsive.
- Make the module responsive for all devices.

### Screenshots

![Screenshot_2022-10-04-10-54-44-25_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/75939390/193741381-34d49fe2-9d6f-4a46-b5c4-e17a9cf2b7d3.jpg)

**Comment by Dawood-Shahid** [comment]
@warmachine028 I want to work on this issue please assign it to me.

**Comment by warmachine028** [comment]
Go ahead!

**Comment by ABHISHEK-PANDEY2** [comment]
Oh not again,it is assigned  , i solved the issue sir , Can i raise the PR 

above 600px width , calender looks like this

![image](https://user-images.githubusercontent.com/95560057/193744535-e5b3cddf-e927-4c3f-b7ea-06f8be3be700.png)

below 600px 

![image](https://user-images.githubusercontent.com/95560057/193744635-1a335c97-42db-4e12-a7bb-7b0e31720222.png)

**Comment by warmachine028** [comment]
@Dawood-Shahid, can you work on another issue please? Actually @ABHISHEK-PANDEY2 already worked on it. Sorry for the inconvenience caused. 

@ABHISHEK-PANDEY2 next time get assigned to an issue before proceeding, that ways issues get assigned on a First come First serve basis🥇

**Comment by ABHISHEK-PANDEY2** [comment]
@warmachine028 i am really sorry , new to all this .. will keep that in mind .
Thanks for the opportunity

**Comment by Dawood-Shahid** [comment]
@warmachine028 ok no issue.

**Comment by Dawood-Shahid** [comment]
@ABHISHEK-PANDEY2 can you try at 320px?

**Comment by ABHISHEK-PANDEY2** [comment]
@Dawood-Shahid 

under 300px 

![image](https://user-images.githubusercontent.com/95560057/193747050-9582b71b-22b0-423b-8588-4780025c3c83.png)

**Comment by warmachine028** [comment]
Looks good! Create the PR

**Comment by ABHISHEK-PANDEY2** [comment]
@warmachine028 Raised the PR
