### ISSUE TITLE
CAPTCHA

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#72]
### Description

- Currently only a static image is displayed in the place of captcha
- Find ways to generate real captcha and match it with user input.
- Discover React libraries to implement captcha Feature.
- The randomly generated captcha image being similar to the current static image is preferred style-wise
- However any new modifications in the generated image is allowed for consideration. 

### Screenshots

- Captcha Image

![Screenshot_2022-10-04-11-05-03-91_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/75939390/193742769-856f17db-0ea0-4053-b919-55443c9f3958.jpg)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by isayakmondal** [comment]
I would like to take up this.

**Comment by warmachine028** [comment]
Great! Assigning you right away

**Comment by isayakmondal** [comment]
Hey after doing `npm i` I'm getting these errors. Could you help me out?
![image](https://user-images.githubusercontent.com/51121313/193790939-8edfa3c3-5281-4ee4-b6dc-c711d870146f.png)
And when I tried to install those dependencies manually I got these.
![image](https://user-images.githubusercontent.com/51121313/193791149-3970b74c-2b29-4af0-b978-b111f52f22f6.png)

**Comment by warmachine028** [comment]
Can you do `npm i --force` that might resolve.

**Comment by isayakmondal** [comment]
> Can you do `npm i --force` that might resolve?
 
 Sorry, I'm still I'm getting these errors on npm start.



Here's the log:
```
Failed to compile.

Module not found: Error: Can't resolve '@progress/kendo-drawing' in 'D:\CODING\contributions\uemcrp\client\node_modules\@progress\kendo-react-pdf\dist\es'
ERROR in ./node_modules/@progress/kendo-react-pdf/dist/es/PDFExport.js 28:0-61
Module not found: Error: Can't resolve '@progress/kendo-drawing' in 'D:\CODING\contributions\uemcrp\client\node_modules\@progress\kendo-react-pdf\dist\es'

ERROR in ./node_modules/@progress/kendo-react-pdf/dist/es/PDFExport.js 32:0-55
Module not found: Error: Can't resolve '@progress/kendo-licensing' in 'D:\CODING\contributions\uemcrp\client\node_modules\@progress\kendo-react-pdf\dist\es'

ERROR in ./node_modules/@progress/kendo-react-pdf/dist/es/savePDF.js 1:0-61
Module not found: Error: Can't resolve '@progress/kendo-drawing' in 'D:\CODING\contributions\uemcrp\client\node_modules\@progress\kendo-react-pdf\dist\es'

webpack compiled with 3 `errors`

```

**Comment by isayakmondal** [comment]
I think this `@progress\kendo-react-pdf` might have some dependencies that it is not installing automatically. But when I'm trying to install them manually I'm getting stuck in a dependency loop.

**Comment by warmachine028** [comment]
Do one thing! Try commenting out this package, then try `npm i`.
![Screenshot 2022-10-04 222914](https://user-images.githubusercontent.com/75939390/193881052-75568ec5-d8dc-40b4-9834-c740564032cd.png)

**Comment by warmachine028** [comment]
Hey @isayakmondal! What is the status of the work

**Comment by isayakmondal** [comment]
Hey, I'm sorry I couldn't make it work. I tried everything :(

**Comment by warmachine028** [comment]
Its alright. This issue will be open unless anyone solves it

**Comment by ozair-dev** [comment]
assign it to me
