### ISSUE TITLE
Mobile Responsiveness: PaydueFees

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#76]
### Description

- PayDueFees Module is successfully created
- But there is a bug in that module
- The module is not responsive
- This must be fixed

### Screenshots

- Pay Due Fees Module
![Screenshot 2022-10-04 234204](https://user-images.githubusercontent.com/75939390/193894311-38c22ea8-76bb-4aae-87fa-1c1b9fbd3986.png)

- Mobile View
![mobile (1)](https://user-images.githubusercontent.com/75939390/193893972-82341050-d5d4-478c-bb67-34d1671d50de.png)

- Laptop view
![Screenshot 2022-10-04 222914](https://user-images.githubusercontent.com/75939390/193893500-173297cb-4d32-4ea4-9eb2-33b41a2720cc.png)

- Code
![code](https://user-images.githubusercontent.com/75939390/193894014-6400eff1-009b-4556-bf66-ba491a53a45a.png)

### Additional information

- Maintain Folder Structure
- Use MUI Components only
- Refrain from creating `.css` files, stick to styled components only.

**Comment by Muhammad-Shahid-Jamal** [comment]
@warmachine028 kindly assign it to me so i can work on it

**Comment by Alcadeus0** [comment]
hi can i work on this

**Comment by warmachine028** [comment]
Yes! Assigning you right away

**Comment by Alcadeus0** [comment]
sweet! working on it asap
