### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#80]
### Description

- There must be a reset button to quickly reset the date 
- There are 2 places which look suitable for the reset button to me (any new suggestions are welcome).
- You must add the reset button in any one position, **remember to maintain the responsiveness of the page**.
- The function of this reset button will be to reset the dates to current date.
- The functionality must not be added right away only the button must be added in.

### Screenshots

![Screenshot 2022-09-06 213724](https://user-images.githubusercontent.com/75939390/188684704-3ff0727b-523e-4c59-9cc1-a2025fb5a56b.jpg)

### Additional information

- Please maintain the mobile responsiveness.
- Only use material UI components.
- Do not install any new Package.
- Make changes to the required file only.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by amanchoudhary18** [comment]
Assign it to me

**Comment by warmachine028** [comment]
good! Assigning right away
