### ISSUE TITLE
Side Panel for Organizational Calendar

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#83]
### Description

- Currently The organizational calendar does nothing.
- It is missing a side Pannel.
- There must a proper side panel in which all holidays must be displayed.
- You can take reference from the below image on how the side panel must look like, (any other good designs are also preferrable).
- You can use [Mui List Components](https://mui.com/material-ui/react-list/#main-content)
- The side panel must look good.
- You can find the holiday list [here](https://uem.edu.in/uem-kolkata/holiday-list)

### Screenshots

- ## Position of side panel
![side pannel](https://user-images.githubusercontent.com/75939390/193998283-9bb6b61b-6072-4bd6-9b82-ae27bbe26714.png)

- ## Mui Docs Side Panel Reference
![side pannel 1](https://user-images.githubusercontent.com/75939390/193998768-c77a49cd-a63e-4c9e-bd62-0d4eeda6e1bb.png)

### Additional information

- Always use styled componets instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by aaushitiwari** [comment]
can you assign this to me?

**Comment by warmachine028** [comment]
Sure! Go ahead with it!

**Comment by aaushitiwari** [comment]
hey, just a doubt you want me to make just the frontend part of the panel right? Also is it okay if I use HTML, CSS to make it?

**Comment by warmachine028** [comment]
Yes only front end part is necessary as of now. Refrain from using plain HTML/CSS.Make use of JSX in React components and Styled Components in Material UI only.

**Comment by warmachine028** [comment]
Hey @aaushitiwari! What is the status of the work?

**Comment by aaushitiwari** [comment]
I don't really know react that much. I could have done it using bootstrap, HTML,CSS and hence i unassigned myself

**Comment by tanishk-23** [comment]
@warmachine028 Can you please assign this issue to me?

**Comment by warmachine028** [comment]
Sure

**Comment by warmachine028** [comment]
Im assigning both of you since this is a critical issue. I want this done ASAP. make sure to star and fork this repo💚

**Comment by warmachine028** [comment]
Hey @tanishk-23, @akarsh-jain-790 what is the progress on this issue?

**Comment by Ts-A** [comment]
Can you assign it to me?
Also clarify on this: 
Desktop view - side panel
How about the mobile view?

**Comment by warmachine028** [comment]
How about we hide it and keep a hamburger icon to toggle it on the top left corner.

**Comment by warmachine028** [comment]
What is the progress?

**Comment by Ts-A** [comment]
submitting a pr in a few hours
