### ISSUE TITLE
Unit Test Details 📇

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#84]
### Description

- The unit test Module is not designed yet.
- Currently the module does nothing but display a test.
- The module must be designed using Material UI only
- You may refer to the given screenshots
- Design the module such that it looks good aesthetically and matches the other UI components.
- Make use of modern Material UI components and take reference from other components 

### Screenshots

- The module
![ut d](https://user-images.githubusercontent.com/75939390/194001968-3cbb65ff-55f6-4d3e-8b2f-0065684f24f8.png)

- The current view of original website
![Screenshot 2022-10-05 124023](https://user-images.githubusercontent.com/75939390/194001962-1552b1a5-34d4-49eb-871e-573aaefafb1e.png)

### Additional information

- Always use styled componets instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by debopriyadey** [comment]
I'll be more than happy to work on it,pls assign me

**Comment by warmachine028** [comment]
Assigned You!
