### ISSUE TITLE
User Image Update Feature

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#90]
### Description

- The user must be able to update their profile images.
- They must hover over the image.
- Then the overlay must be visible with a camera icon in the center
- **The camera Icon must be white instead of black**
- There must be a subtle transition. The overlay coming from bottom to up on hover.
- User must be able to click on the camera icon in the center of the overlay

### Screenshots

- Hover layout
![Screenshot 2022-10-06 231336](https://user-images.githubusercontent.com/75939390/194383360-ef673431-d2e4-4aa2-bc57-2343744e3a29.png)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by IRSHIT033** [comment]
Can assign me on this

**Comment by warmachine028** [comment]
Sure!

**Comment by warmachine028** [comment]
what is the status of the job @IRSHIT033 ?

**Comment by DarkSoul26** [comment]
@warmachine028 I would like to work on this issue.

**Comment by warmachine028** [comment]
Sure!

**Comment by warmachine028** [comment]
What is the progress on this issue? @DarkSoul26

**Comment by DarkSoul26** [comment]
I apologise @warmachine028, but I'm not able to find a correct solution to this issue.

**Comment by warmachine028** [comment]
Alright I will kepp this issue open incase anyone is able to solve it. I will unassign you from it as of now

**Comment by boltkk95** [comment]
@warmachine028  if no one is working on this, i would like to

**Comment by warmachine028** [comment]
Sure, I've assigned you this issue

**Comment by boltkk95** [comment]
thanks

**Comment by boltkk95** [comment]
@warmachine028  Regarding the matter of storing the profile picture uploaded by users, how do you want me to proceed?

**Comment by warmachine028** [comment]
Right now just the ui Part is necessary. The user must be able to choose the image from their devices. The rest storage logic will be added eventually after the backend is ready

**Comment by boltkk95** [comment]
Ok. Got it

**Comment by boltkk95** [comment]
@warmachine028 I'm interested to work on more issues .. Is there any which you think I can can take up and resolve ?

**Comment by boltkk95** [comment]
@warmachine028  i have issued the pull request for the current issue, please look in to it

**Comment by warmachine028** [comment]
@boltkk95  make sure to star this repository for more issues
