### ISSUE TITLE
Font must be smaller

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#97]
### Description

- This font in the given image below must be smaller in mobile devices
- Do not directly change the styled for desktop devices in the `styles.js` file.
- Use Styled Component breakPoints to adjust the fontSize for mobile devices of that specific Typography class.
- Only change the fontSize, don't deviate from task

### Screenshots

![mobile](https://user-images.githubusercontent.com/75939390/195422958-e780f59a-35a2-4fd3-b783-b2d7d82cdfd6.png)

### Additional information

- Maintain Folder Structure
- Always use styled componets and MUI components instead of plain CSS.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Harsh-garg-coder** [comment]
can you assign this issue to me?

**Comment by warmachine028** [comment]
Yes, Will assign you right away!

**Comment by Harsh-garg-coder** [comment]
thank you
