### ISSUE TITLE
[OTHER] Server Side

### ISSUE THREAD

**Issue by Ts-A** [warmachine028/uemcrp#99]
### What would you like to share?

At the moment, I don't find any server code but in [Setup.md](https://github.com/warmachine028/uemcrp/blob/main/rules/SETUP.md) it does mention the way to run the sever. If you take contributions setting up an express server and working on it from scratch, I could work on it.

**Comment by warmachine028** [comment]
Sure! Why not. Assigning you.

**Comment by warmachine028** [comment]
Hi @Ts-A ! What is the progress?

**Comment by Ts-A** [comment]
> Hi @Ts-A ! What is the progress?

- Setup basic expressjs with dotenv
- MongoDB localhost connection check
- Sample user model
- Sample REST APIs for user CRUD

Working on setting up user auth using jwt and secure password storing.

Will submit a PR in a few hours for you to review.

**Comment by Ts-A** [comment]
If you have a specific user model for key-value pairs, you can tag it here so I can add it as well

**Comment by Ts-A** [comment]
Since we need a user model to proceed with password and user auth, I'll skip user model.
